name: Sync GitHub to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Sync to Hugging Face
        uses: huggingface/hub-sync@v0.1.6   
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: atufakhan/repo-name
          hf_token: ${{ secrets.HF_TOKEN }}
